services:
  api:
    build:
      context: .
      target: builder
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    env_file: .env
    environment:
      - NODE_ENV=development
      - PORT=8080
